### ISSUE TITLE
Trying to port the code to C# 

### ISSUE THREAD

**Issue by ahmad-crossplatform** [mfkl/LibVLCSharp-readonly#23]
Hello there I have started a small Project , to port the java code into C#  still long way to finish though
What do you think of this idea ? 
https://github.com/ahmad-crossplatform/Libvlc.Xamarin.Android

**Comment by mfkl** [comment]
Hey,
Yes that's basically what I'm doing in the Android branch. Have a look.
You will have JNI issues when implementing the AWindow class in C# though (mono bug).

**Comment by ahmad-crossplatform** [comment]
Cool well I am actually taking every class in the java one and convert it to C# , later on I am planning to have the refactoring and include events, for example, instead of the ugly Ilistener stuff . 
Shall we collaborate ? would be nice to work together since we have the same the goals

**Comment by mfkl** [comment]
You're welcome to fork and open PRs ;-)

However, LibVLCSharp's API will not be a 1:1 mapping of the Java code you might have come across.

**Comment by ahmad-crossplatform** [comment]
Do you have any slack or gitter to communicate , I might have some questions regarding the fody and  CppSharp and some general thoughts too .

**Comment by mfkl** [comment]
https://gitter.im/libvlcsharp

You can disable locally the fody plugin if it fails, I need to update it and make some changes.
As for CppSharp, it's being used anymore so you don't need to worry about this.
