### ISSUE TITLE
Xamarin forms PCL or .NetStandard

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [mfkl/LibVLCSharp-readonly#27]
How do I implement this in xamarin forms? I'd like to sample it in xaml, It's possible?

**Comment by mfkl** [comment]
Hello,

Yes it's possible, I'm currently finishing to implement it. Will be done soon and ping you here.

**Comment by andersonvieiragomeslopes** [comment]
Sorry, I could not implement, do you have any samples to build and run?

**Comment by mfkl** [comment]
Hi @andersonvieiragomeslopes,

Have some issues with nuget packaging, that's the final step before it is uploaded to nuget and then you can use it easily. Will ping you here when thats done, soon I hope. You can track progress here https://github.com/mfkl/LibVLCSharp/pull/32.

Stay tuned

**Comment by andersonvieiragomeslopes** [comment]
An attempt to be made in videos? M3u8? Are live content streaming videos, for me it is really very important to play videos in that format, would it be possible? Thanks in advance for your attention.

**Comment by mfkl** [comment]
Should be possible.

**Comment by andersonvieiragomeslopes** [comment]
I figured this out, because it's vlc, I'm waiting for the upload, good work.

**Comment by mfkl** [comment]
Yeah, if you can play it in the vlc desktop app, usually it's a good bet that it will be possible to do with LibVLCSharp (for most things).

**Comment by andersonvieiragomeslopes** [comment]
And is it really possible to use in conjunction with Chromecast? I'm mirroring on youtube for example.

**Comment by mfkl** [comment]
Try with a recent desktop vlc app (3.0.2 for example). If you can do so, then yeah. I've casted HTTP streams to the chromecast before.

**Comment by andersonvieiragomeslopes** [comment]
Sorry, I expressed myself a bit bad, I refer to xamarin forms, as soon as you finish packaging, will it be possible to stream the videos to SmartTv using your plugin?

**Comment by mfkl** [comment]
I don't know what "SmartTv" is. If you mean chromecast, yes.

**Comment by andersonvieiragomeslopes** [comment]
SmartTv = Televisions with internet access, :)

**Comment by mfkl** [comment]
No we don't do SmartTv integration, only chromecast for now.

**Comment by andersonvieiragomeslopes** [comment]
Just to better understand, the integration is similar to what youtube does when there is a chromecast in the same ssid(Internet wireless or wired internet)?

**Comment by mfkl** [comment]
Yes. Essentially this https://github.com/kakone/GoogleCast (but a bit different implementation wise)

**Comment by mfkl** [comment]
Have a look at the readme, I updated it with a link to the nuget package. This is the first pre-release package though, so expect some bugs ;-)
Will push a Forms package soon.
