### ISSUE TITLE
IEnumerable or Array for public API

### ISSUE THREAD

**Issue by mfkl** [mfkl/LibVLCSharp-readonly#7]
@jeremyVignelles

**Comment by jeremyVignelles** [comment]
It depends on what we are trying to do.
When the size of the returned collection is known in advance and doesn't change, my vote goes to using an Array

**Comment by mfkl** [comment]
How about `Span<T>`?

**Comment by jeremyVignelles** [comment]
Span<T> is pretty new, I'm still wondering how it works. what are the benefits of using it rather than using an array? in which cases would that be profitable?

**Comment by mfkl** [comment]
This link has some information http://adamsitnik.com/Span/

Looks like there is an implicit cast operator from `T[]` to `Span<T>`. Let's go with Arrays for now.
